### ISSUE TITLE
Not working. Get error.

### ISSUE THREAD

**Issue by Tolithe** [vijjo/huongdan_deck_to_audio#1]
Error
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.22 (0ecc189a) Python 3.8.0 Qt 5.14.1 PyQt 5.14.1
Platform: Windows 10
Flags: frz=True ao=True sv=1
Add-ons, last update check: 2020-05-30 17:34:18

Caught exception:
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Anki2\addons21\2095022381\export_to_audio.py", line 464, in _on_accept
    combines = generate_audio(deck_name,
  File "C:\Users\USER\AppData\Roaming\Anki2\addons21\2095022381\export_to_audio.py", line 196, in generate_audio
    combines.append(combine_audios(audios,
  File "C:\Users\USER\AppData\Roaming\Anki2\addons21\2095022381\export_to_audio.py", line 78, in combine_audios
    tmp_audio = AudioSegment.from_file(audio_name)
  File "C:\Users\USER\AppData\Roaming\Anki2\addons21\2095022381\pydub\audio_segment.py", line 665, in from_file
    info = mediainfo_json(orig_file)
  File "C:\Users\USER\AppData\Roaming\Anki2\addons21\2095022381\pydub\utils.py", line 264, in mediainfo_json
    res = Popen(command, stdin=stdin_parameter, stdout=PIPE, stderr=PIPE)
  File "subprocess.py", line 854, in init
  File "subprocess.py", line 1307, in _execute_child
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by vijjo** [comment]
Bởi vì card không có audio ở mặt sau thôi.
